- Profile 1: Amina Diallo
- Name: Amina Diallo
- Age: 34
- Gender: Female
- Marital Status: Married
- Number of Dependents: 4 (3 children, 1 elderly parent)
- Location: Zinder Region
- Displacement Status: Not displaced
- Health Status: Generally healthy, but has a chronic respiratory condition
- Access to Healthcare: Limited; nearest clinic is 15 km away
- Education Level: Primary education (completed)
- Employment Status: Farmer and livestock keeper
- Income Level: Approximately $200 per year
- Housing Conditions: Traditional mud-brick house with thatched roof
- Food Security: Occasionally faces food shortages during the dry season
- Water and Sanitation Access: Access to a borehole, but water quality is poor
- Social Support Networks: Strong community ties; participates in local women's group
- Coping Mechanisms: Engages in barter trade with neighbors
- Cultural Background: Hausa ethnic group
- Specific Needs: Access to better healthcare and agricultural training

- Profile 2: Moussa Ibrahim
- Name: Moussa Ibrahim
- Age: 45
- Gender: Male
- Marital Status: Widowed
- Number of Dependents: 2 (both children)
- Location: Maradi Region
- Displacement Status: Internally displaced due to conflict
- Health Status: Good, but one child has a disability
- Access to Healthcare: Limited; relies on local healers
- Education Level: Secondary education (incomplete)
- Employment Status: Part-time herder
- Income Level: Approximately $150 per year
- Housing Conditions: Temporary shelter made of tarpaulin
- Food Security: Struggles to provide enough food for his family
- Water and Sanitation Access: Access to a communal well
- Social Support Networks: Limited; relies on extended family
- Coping Mechanisms: Engages in small-scale trading
- Cultural Background: Tuareg ethnic group
- Specific Needs: Support for his child's disability and food assistance

- Profile 3: Fatoumata Souley
- Name: Fatoumata Souley
- Age: 28
- Gender: Female
- Marital Status: Married
- Number of Dependents: 3 (2 children, 1 sibling)
- Location: Tillabéri Region
- Displacement Status: Not displaced
- Health Status: Healthy, but experiences seasonal allergies
- Access to Healthcare: Moderate; local clinic available
- Education Level: Completed secondary education
- Employment Status: Farmer and market vendor
- Income Level: Approximately $300 per year
- Housing Conditions: Simple house with access to basic amenities
- Food Security: Generally secure, but relies on seasonal crops
- Water and Sanitation Access: Access to a well with clean water
- Social Support Networks: Active in community groups
- Coping Mechanisms: Savings group participation
- Cultural Background: Fulani ethnic group
- Specific Needs: Training in sustainable farming practices

- Profile 4: Ibrahim Adamou
- Name: Ibrahim Adamou
- Age: 50
- Gender: Male
- Marital Status: Married
- Number of Dependents: 6 (5 children, 1 elderly parent)
- Location: Agadez Region
- Displacement Status: Not displaced
- Health Status: Chronic back pain
- Access to Healthcare: Limited; must travel to the nearest town
- Education Level: No formal education
- Employment Status: Full-time herder
- Income Level: Approximately $400 per year
- Housing Conditions: Traditional tent structure
- Food Security: Generally secure, but faces challenges during droughts
- Water and Sanitation Access: Access to a seasonal river
- Social Support Networks: Strong family and clan ties
- Coping Mechanisms: Shares resources with neighbors
- Cultural Background: Beri-Beri ethnic group
- Specific Needs: Access to healthcare for chronic pain management

- Profile 5: Salima Mahamadou
- Name: Salima Mahamadou
- Age: 32
- Gender: Female
- Marital Status: Single
- Number of Dependents: 1 (a young child)
- Location: Dosso Region
- Displacement Status: Not displaced
- Health Status: Generally healthy, but has experienced postpartum complications
- Access to Healthcare: Moderate; local health post available, but often lacks supplies
- Education Level: Completed primary education
- Employment Status: Small-scale farmer and artisan (weaver)
- Income Level: Approximately $250 per year
- Housing Conditions: Simple mud-brick house with a thatched roof
- Food Security: Faces food insecurity during the lean season
- Water and Sanitation Access: Access to a nearby river, but sanitation facilities are inadequate
- Social Support Networks: Active in a women's cooperative for artisans
- Coping Mechanisms: Participates in community barter systems and savings groups
- Cultural Background: Zarma ethnic group
- Specific Needs: Access to maternal health services and training in sustainable farming techniques

- Profile 6: Abdoulaye Kone
- Name: Abdoulaye Kone
- Age: 40
- Gender: Male
- Marital Status: Married
- Number of Dependents: 5 (4 children, 1 elderly uncle)
- Location: Tahoua Region
- Displacement Status: Not displaced
- Health Status: Generally healthy, but suffers from occasional malaria
- Access to Healthcare: Limited; relies on traditional medicine for minor ailments
- Education Level: Incomplete primary education
- Employment Status: Full-time farmer and part-time herder
- Income Level: Approximately $350 per year
- Housing Conditions: Traditional house made of mud with a thatched roof
- Food Security: Generally secure, but struggles during drought years
- Water and Sanitation Access: Access to a community well, but water is often scarce
- Social Support Networks: Strong ties with extended family and local community
- Coping Mechanisms: Engages in seasonal migration for work
- Cultural Background: Songhai ethnic group
- Specific Needs: Access to agricultural training and improved water sources

- Profile 7: Mariama Tchana
- Name: Mariama Tchana
- Age: 27
- Gender: Female
- Marital Status: Divorced
- Number of Dependents: 2 (both children)
- Location: Niamey Region
- Displacement Status: Not displaced
- Health Status: Healthy, but has limited access to reproductive health services
- Access to Healthcare: Moderate; local clinic available but often lacks staff
- Education Level: Secondary education (completed)
- Employment Status: Market vendor and part-time farmer
- Income Level: Approximately $200 per year
- Housing Conditions: Small rented room in a communal setting
- Food Security: Faces food insecurity, especially during the rainy season
- Water and Sanitation Access: Access to a public tap, but sanitation facilities are poor
- Social Support Networks: Limited; relies on friends and neighbors for support
- Coping Mechanisms: Participates in local savings groups
- Cultural Background: Hausa ethnic group
- Specific Needs: Access to microfinance and vocational training

- Profile 8: Oumarou Sani
- Name: Oumarou Sani
- Age: 55
- Gender: Male
- Marital Status: Married
- Number of Dependents: 7 (6 children, 1 elderly mother)
- Location: Diffa Region
- Displacement Status: Internally displaced due to regional conflict
- Health Status: Chronic hypertension
- Access to Healthcare: Limited; must travel to a distant clinic for treatment
- Education Level: No formal education
- Employment Status: Full-time herder
- Income Level: Approximately $300 per year
- Housing Conditions: Temporary shelter made of plastic sheeting
- Food Security: Struggles to provide enough food for his family
- Water and Sanitation Access: Access to a nearby river, but sanitation is inadequate
- Social Support Networks: Limited; relies on fellow displaced individuals
- Coping Mechanisms: Engages in communal farming efforts
- Cultural Background: Kanuri ethnic group
- Specific Needs: Food assistance and access to healthcare for chronic conditions

- Profile 9: Hawa Aboubakar
- Name: Hawa Aboubakar
- Age: 30
- Gender: Female
- Marital Status: Married
- Number of Dependents: 3 (2 children, 1 disabled sibling)
- Location: Agadez Region
- Displacement Status: Not displaced
- Health Status: Generally healthy, but her sibling requires special care
- Access to Healthcare: Moderate; local health center available but often lacks resources
- Education Level: Completed primary education
- Employment Status: Farmer and craftsperson (pottery)
- Income Level: Approximately $280 per year
- Housing Conditions: Simple mud-brick house with basic amenities
- Food Security: Generally secure, but faces challenges during the dry season
- Water and Sanitation Access: Access to a borehole with clean water
- Social Support Networks: Active in local women's cooperative
- Coping Mechanisms: Participates in community events and shares resources with neighbors
- Cultural Background: Tuareg ethnic group
- Specific Needs: Access to training in sustainable pottery techniques and support for her sibling's care

- Profile 10: Souleymane Mahamane
- Name: Souleymane Mahamane
- Age: 38
- Gender: Male
- Marital Status: Married
- Number of Dependents: 4 (3 children, 1 elderly aunt)
- Location: Dosso Region
- Displacement Status: Not displaced
- Health Status: Generally healthy, but has occasional gastrointestinal issues
- Access to Healthcare: Moderate; local clinic available but often lacks medications
- Education Level: Incomplete secondary education
- Employment Status: Full-time farmer and part-time trader
- Income Level: Approximately $400 per year
- Housing Conditions: Traditional house with a thatched roof and a small garden
- Food Security: Generally secure, but faces challenges during the lean season
- Water and Sanitation Access: Access to a nearby well with clean water
- Social Support Networks: Strong community ties; involved in local agricultural cooperatives
- Coping Mechanisms: Engages in crop diversification and shares resources with neighbors
- Cultural Background: Zarma ethnic group
- Specific Needs: Access to agricultural training and improved market access for his products

